name: build & publish Docker image

on:
  push:
    branches:
      - main

jobs:
  test:
    name: lint & test
    uses: './.github/workflows/test.yml'

  build-and-publish:
    name: build & publish Docker image
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: build Docker image & push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            derhuerst/generate-herrenberg-gtfs-flex:latest
